--- #YAML:1.0
name:               RT-Client-REST
version:            0.4
abstract:           ~
author:  []
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Encode:               0
    Error:                0
    Exception::Class:     0
    HTTP::Cookies:        0
    HTTP::Request::Common:  0
    LWP:                  0
    Params::Validate:     0
    Test::Exception:      0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
