---
abstract: 'talk to RT installation using REST protocol.'
author:
  - 'Original /usr/bin/rt was written by Abhijit Menon-Sen <ams@wiw.org>.  rt'
build_requires:
  ExtUtils::MakeMaker: 6.36
  Test::Exception: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Client-REST
no_index:
  directory:
    - examples
    - inc
    - t
requires:
  DateTime: 0
  DateTime::Format::DateParse: 0
  Encode: 0
  Error: 0
  Exception::Class: 0
  HTTP::Cookies: 0
  HTTP::Request::Common: 0
  LWP: 0
  Params::Validate: 0
  URI: 0
resources:
  license: http://dev.perl.org/licenses/
  repository: https://github.com/RT-Client-REST/RT-Client-REST.git
version: 0.49
