# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         RT-Client-REST
version:      0.21
version_from: lib/RT/Client/REST.pm
installdirs:  site
requires:
    Error:                         0
    Exception::Class:              0
    HTTP::Cookies:                 0
    HTTP::Request::Common:         0
    LWP:                           0
    Params::Validate:              0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
